/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Holds an exclusive advisory lock on a file. Drop releases the
 * lock — both via explicit `release()` and via JS garbage collection
 * (napi-rs runs a finalizer on the underlying File handle). On
 * process death the kernel releases the lock unconditionally.
 */
export declare class FileLock {
  /**
   * Release the lock. Idempotent — safe to call multiple times.
   * Equivalent to letting the JS handle be garbage-collected, but
   * gives the caller deterministic timing.
   */
  release(): void
}

/**
 * Try to acquire an exclusive lock on `path`. Creates the file if
 * it doesn't exist. Returns a `FileLock` handle on success.
 *
 * On contention, throws an error with `code === "LOCKED"`. Filesystem
 * errors (permission denied, etc.) throw with code `"FS"`.
 */
export declare function tryAcquire(path: string): FileLock
